### ISSUE TITLE
Repository unavailable?

### ISSUE THREAD

**Issue by alaendle** [typelead/etlas-index#6]
`etlas update` returns a 404 while executing the following command:

"C:\Users\user\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\usr\bin\curl.exe" "https://6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.6.6\packages\index" "--output" "C:\Users\user\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.6.6\packages\index1916915724" "--location" "--write-out" "%{http_code}" "--user-agent" "etlas/1.0.0.0 (windows; x86_64)" "--silent" "--show-error" "--dump-header" "C:\Users\user\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.6.6\packages\curl-headers1147829358.txt"

**Comment by rahulmutt** [comment]
I assume you're on Windows? Try doing a `cleaninstall.sh` from the most recent commit on the `eta` repo. I fixed the path handling in that commit.

**Comment by alaendle** [comment]
Yes, I'm working on a windows machine - and now everything works as expected. Many thanks!
